### ISSUE TITLE
Is not working 

### ISSUE THREAD

**Issue by TeaAndSugar-1** [negrifelipe/ServerStatusBot#6]
it will not actually ping the server ip and create anything it keeps saying 

Timeout on error on {server ip}

**Comment by 01-Feli** [comment]
Can you please post your config, hide your token

**Comment by TeaAndSugar-1** [comment]
I cannot provide it right now but at 5 UTC I can sorry for this
inconvenience

**Comment by adarsh-sk6** [comment]
Which node bash or node.js or any

**Comment by TeaAndSugar-1** [comment]
Um I cant even remember what this is it has been nearly a year
